import type { AppUser } from './types';

export const mockUsers: AppUser[] = [
  {
    id: '1',
    firstName: 'Preston',
    lastName: 'Dues',
    fullName: 'Preston Dues',
    username: 'pdues',
    role: 'Admin',
    homeDepartment: 'Packaging',
    shift: 'Packaging 1st Shift',
    status: 'Active',
    employeeId: 'KB1001',
    hireDate: '2023-04-10',
    birthday: '2000-08-14',
    probationary: false,
    trainerEnabled: true,
    email: 'preston@example.com',
  },
  {
    id: '2',
    firstName: 'Alicia',
    lastName: 'Brown',
    fullName: 'Alicia Brown',
    username: 'abrown',
    role: 'Supervisor',
    homeDepartment: 'Baking',
    shift: 'Baking 3rd Shift',
    status: 'Active',
    employeeId: 'KB1042',
    hireDate: '2024-01-12',
    birthday: '1994-03-02',
    probationary: false,
    trainerEnabled: true,
    email: 'alicia@example.com',
  },
  {
    id: '3',
    firstName: 'Marcus',
    lastName: 'Hill',
    fullName: 'Marcus Hill',
    username: 'mhill',
    role: 'Operator',
    homeDepartment: 'Packaging',
    shift: 'Packaging 1st Shift',
    status: 'Active',
    employeeId: 'KB1088',
    hireDate: '2025-02-01',
    birthday: '1998-11-20',
    probationary: true,
    trainerEnabled: false,
    email: 'marcus@example.com',
  },
  {
    id: '4',
    firstName: 'Jasmine',
    lastName: 'Cole',
    fullName: 'Jasmine Cole',
    username: 'jcole',
    role: 'FSQA',
    homeDepartment: 'FSQA',
    shift: 'Packaging 1st Shift',
    status: 'Active',
    employeeId: 'KB1120',
    hireDate: '2022-09-18',
    birthday: '1991-06-07',
    probationary: false,
    trainerEnabled: true,
    email: 'jasmine@example.com',
  },
  {
    id: '5',
    firstName: 'Tyler',
    lastName: 'Reed',
    fullName: 'Tyler Reed',
    username: 'treed',
    role: 'Team Member',
    homeDepartment: 'Baking',
    shift: 'Baking 1st Shift',
    status: 'Inactive',
    employeeId: 'KB1173',
    hireDate: '2024-07-08',
    birthday: '2001-01-12',
    probationary: false,
    trainerEnabled: false,
    email: 'tyler@example.com',
  },
];